login: &login
  adapter: mysql
  username: root
  password: 

development:
  <<: *login
  database: donebox_development

test:
  <<: *login
  database: donebox_test

production:
  <<: *login
  database: donebox_production
